# Server
server.port=${PORT:8080}
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=https://resume-registry-service-production.up.railway.app/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway Discovery Locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true