# Server
server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=https://resume-registry-service-production.up.railway.app/eureka

# Gateway doesn't need to be discovered by others
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true

# Gateway Discovery Locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true